Repository bookand-team/Bookand.Backend, pull requests merged in 2023-03, with the labels that each got.

#29 [bookand dev/16] 피드백 API 구현
  src/main/java/kr/co/bookand/backend/account/domain/Account.java
  src/main/java/kr/co/bookand/backend/bookstore/controller/BookStoreController.java
  src/main/java/kr/co/bookand/backend/bookstore/domain/BookStore.java
  src/main/java/kr/co/bookand/backend/bookstore/repository/ReportBookStoreRepository.java
  src/main/java/kr/co/bookand/backend/bookstore/service/BookStoreService.java
  src/main/java/kr/co/bookand/backend/common/domain/dto/PageResponse.java
  src/main/java/kr/co/bookand/backend/common/exception/ErrorCode.java
  src/main/java/kr/co/bookand/backend/feedback/controller/FeedbackController.java
  src/main/java/kr/co/bookand/backend/feedback/domain/Feedback.java
  src/main/java/kr/co/bookand/backend/feedback/domain/FeedbackTarget.java
  src/main/java/kr/co/bookand/backend/feedback/domain/FeedbackType.java
  src/main/java/kr/co/bookand/backend/feedback/domain/dto/FeedbackDto.java
  src/main/java/kr/co/bookand/backend/feedback/exception/FeedbackException.java
  src/main/java/kr/co/bookand/backend/feedback/repository/FeedbackRepository.java
  src/main/java/kr/co/bookand/backend/feedback/service/FeedbackService.java
Labels: 😎 Feature

#31 [bookand dev/11] 대시보드 API 구현
  src/main/java/kr/co/bookand/backend/account/domain/Role.java
  src/main/java/kr/co/bookand/backend/account/repository/AccountRepository.java
  src/main/java/kr/co/bookand/backend/article/repository/ArticleRepository.java
  src/main/java/kr/co/bookand/backend/bookmark/repository/BookmarkRepository.java
  src/main/java/kr/co/bookand/backend/bookstore/repository/BookStoreRepository.java
  src/main/java/kr/co/bookand/backend/bookstore/repository/ReportBookStoreRepository.java
  src/main/java/kr/co/bookand/backend/dashboard/controller/DashBoardController.java
  src/main/java/kr/co/bookand/backend/dashboard/domain/DashBoard.java
  src/main/java/kr/co/bookand/backend/dashboard/domain/dto/DashBoardDto.java
  src/main/java/kr/co/bookand/backend/dashboard/repository/DashBoardRepository.java
  src/main/java/kr/co/bookand/backend/dashboard/service/DashBoardService.java
  src/main/java/kr/co/bookand/backend/feedback/repository/FeedbackRepository.java
Labels: 😎 Feature

#32 [bookand dev/35] 에러 코드 한글화
  src/main/java/kr/co/bookand/backend/account/exception/AccountException.java
  src/main/java/kr/co/bookand/backend/account/service/AuthService.java
  src/main/java/kr/co/bookand/backend/article/exception/ArticleException.java
  src/main/java/kr/co/bookand/backend/bookmark/exception/BookmarkException.java
  src/main/java/kr/co/bookand/backend/bookstore/exception/BookStoreException.java
  src/main/java/kr/co/bookand/backend/common/exception/ApiErrorResponse.java
  src/main/java/kr/co/bookand/backend/common/exception/ErrorCode.java
  src/main/java/kr/co/bookand/backend/common/exception/GlobalExceptionHandler.java
  src/main/java/kr/co/bookand/backend/config/jwt/exception/ExceptionHandlerFilter.java
  src/main/java/kr/co/bookand/backend/config/jwt/exception/JwtAccessDeniedHandler.java
  src/main/java/kr/co/bookand/backend/config/jwt/exception/JwtAuthenticationEntryPoint.java
  src/main/java/kr/co/bookand/backend/config/jwt/exception/JwtException.java
  src/main/java/kr/co/bookand/backend/feedback/exception/FeedbackException.java
  src/main/java/kr/co/bookand/backend/feedback/service/FeedbackService.java
  src/main/java/kr/co/bookand/backend/notification/exception/NotificationException.java
  src/main/java/kr/co/bookand/backend/policy/exception/PolicyException.java
  src/main/java/kr/co/bookand/backend/util/s3/exception/AwsS3Exception.java
Labels: 🛠️ Refactoring

#33 [bookand dev/36] 탈퇴 처리 API, 부정 정책 적용
  src/main/java/kr/co/bookand/backend/account/controller/AccountController.java
  src/main/java/kr/co/bookand/backend/account/domain/Account.java
  src/main/java/kr/co/bookand/backend/account/domain/AccountStatus.java
  src/main/java/kr/co/bookand/backend/account/domain/RevokeAccount.java
  src/main/java/kr/co/bookand/backend/account/domain/RevokeType.java
  src/main/java/kr/co/bookand/backend/account/domain/Role.java
  src/main/java/kr/co/bookand/backend/account/domain/SuspendedAccount.java
  src/main/java/kr/co/bookand/backend/account/domain/dto/AuthDto.java
  src/main/java/kr/co/bookand/backend/account/domain/dto/RevokeDto.java
  src/main/java/kr/co/bookand/backend/account/repository/RevokeAccountRepository.java
  src/main/java/kr/co/bookand/backend/account/repository/SuspendedAccountRepository.java
  src/main/java/kr/co/bookand/backend/account/service/AccountService.java
  src/main/java/kr/co/bookand/backend/account/service/AuthService.java
  src/main/java/kr/co/bookand/backend/account/util/AccountUtil.java
  src/main/java/kr/co/bookand/backend/common/domain/BaseEntity.java
  src/main/java/kr/co/bookand/backend/common/exception/ErrorCode.java
  src/main/java/kr/co/bookand/backend/config/jwt/RefreshToken.java
  src/main/java/kr/co/bookand/backend/config/jwt/RefreshTokenRepository.java
Labels: 😎 Feature, 🛠️ Refactoring

#35 [bookand dev/12] 카카오 지도 검색 API 구현
  src/main/java/kr/co/bookand/backend/bookstore/domain/dto/BookStoreDto.java
  src/main/java/kr/co/bookand/backend/common/exception/ErrorCode.java
  src/main/java/kr/co/bookand/backend/map/controller/MapController.java
  src/main/java/kr/co/bookand/backend/map/exception/MapException.java
  src/main/java/kr/co/bookand/backend/map/service/MapService.java
Labels: 😎 Feature

#36 [bookand dev/42] 아티클 수정 및 북마크 오류 수정
  .gitignore
  src/main/java/kr/co/bookand/backend/article/controller/ArticleController.java
  src/main/java/kr/co/bookand/backend/article/domain/Article.java
  src/main/java/kr/co/bookand/backend/article/domain/dto/ArticleDto.java
  src/main/java/kr/co/bookand/backend/bookmark/controller/BookmarkController.java
  src/main/java/kr/co/bookand/backend/bookmark/domain/dto/BookmarkDto.java
  src/main/java/kr/co/bookand/backend/bookmark/repository/BookmarkArticleRepository.java
  src/main/java/kr/co/bookand/backend/bookmark/service/BookmarkService.java
  src/main/java/kr/co/bookand/backend/bookstore/domain/dto/BookStoreDto.java
  src/main/java/kr/co/bookand/backend/common/exception/ErrorCode.java
  src/main/java/kr/co/bookand/backend/config/SwaggerConfig.java
  src/main/java/kr/co/bookand/backend/feedback/domain/dto/FeedbackDto.java
  src/main/java/kr/co/bookand/backend/policy/controller/PolicyController.java
  src/main/java/kr/co/bookand/backend/util/dummy/ArticleBookStoreDummyData.java
Labels: 🐛 bug, 🛠️ Refactoring

#37 [bookand dev/39] 커서 기반 페이징 처리
  src/main/java/kr/co/bookand/backend/article/controller/ArticleController.java
  src/main/java/kr/co/bookand/backend/article/domain/dto/ArticleDto.java
  src/main/java/kr/co/bookand/backend/article/repository/ArticleRepository.java
  src/main/java/kr/co/bookand/backend/article/repository/ArticleRepositoryCustom.java
  src/main/java/kr/co/bookand/backend/article/repository/ArticleRepositoryImpl.java
  src/main/java/kr/co/bookand/backend/article/service/ArticleService.java
  src/main/java/kr/co/bookand/backend/bookmark/controller/BookmarkController.java
  src/main/java/kr/co/bookand/backend/bookmark/domain/dto/BookmarkDto.java
  src/main/java/kr/co/bookand/backend/bookmark/repository/BookmarkArticleRepository.java
  src/main/java/kr/co/bookand/backend/bookmark/repository/BookmarkArticleRepositoryCustom.java
  src/main/java/kr/co/bookand/backend/bookmark/repository/BookmarkArticleRepositoryImpl.java
  src/main/java/kr/co/bookand/backend/bookmark/repository/BookmarkBookStoreRepository.java
  src/main/java/kr/co/bookand/backend/bookmark/repository/BookmarkBookStoreRepositoryCustom.java
  src/main/java/kr/co/bookand/backend/bookmark/repository/BookmarkBookStoreRepositoryImpl.java
  src/main/java/kr/co/bookand/backend/bookmark/service/BookmarkService.java
  src/main/java/kr/co/bookand/backend/bookstore/domain/dto/BookStoreDto.java
  src/main/java/kr/co/bookand/backend/common/domain/dto/PageResponse.java
  src/main/java/kr/co/bookand/backend/common/exception/ErrorCode.java
  src/main/java/kr/co/bookand/backend/notification/controller/NotificationController.java
  src/main/java/kr/co/bookand/backend/notification/repository/NotificationRepository.java
  src/main/java/kr/co/bookand/backend/notification/repository/NotificationRepositoryCustom.java
  src/main/java/kr/co/bookand/backend/notification/repository/NotificationRepositoryImpl.java
  src/main/java/kr/co/bookand/backend/notification/service/NotificationService.java
  src/main/java/kr/co/bookand/backend/util/dummy/AccountDummyData.java
  src/main/java/kr/co/bookand/backend/util/dummy/ArticleBookStoreDummyData.java
  src/main/java/kr/co/bookand/backend/util/dummy/NotificationDummyData.java
  src/main/java/kr/co/bookand/backend/util/dummy/PolicyDummyData.java
Labels: 🐛 bug, 😎 Feature, 🛠️ Refactoring
